version: "3.9"
services:
  service-registry:
    build:
      context: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - service-registry
    environment:
      AUTH_SERVICE_URL: http://auth-service:8085

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/quiz-users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  question-service:
    build:
      context: ./question-service
    container_name: question-service
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - question-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://question-db:5432/quizapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/

  quiz-service:
    build:
      context: ./quiz-service
    container_name: quiz-service
    ports:
      - "8090:8090"
    depends_on:
      - service-registry
      - quiz-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://quiz-db:5432/quizdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/

  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiz-users
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  question-db:
    image: postgres:15-alpine
    container_name: question-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quizapp
    ports:
      - "5434:5432"
    volumes:
      - question-db-data:/var/lib/postgresql/data

  quiz-db:
    image: postgres:15-alpine
    container_name: quiz-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quizdb
    ports:
      - "5435:5432"
    volumes:
      - quiz-db-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  auth-db-data:
  question-db-data:
  quiz-db-data:
